services:
  - type: web
    name: notetaker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn notetaker.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: notetaker-db
          property: connectionString

databases:
  - name: notetaker-db
