# Generated by Django 5.2.4 on 2025-07-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('movies', 'Movies'), ('books', 'Books'), ('songs', 'Songs'), ('random', 'Random')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(help_text='For bullets, use one item per line.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
